version: '3.8'

services:

  database:
    image: postgres:alpine
    container_name: database
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - ./docker_volumes/pgdata:/var/lib/postresql/data
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - 5432:5432


  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050
    depends_on:
      - database

  backend:
    build: .
    container_name: backend
    command: run head
    tty: true
    ports:
    - 8000:8000
    depends_on:
      - database
